from time import time

#--------------------Class Laser Weapon--------------------------
#   Simulates behavior of a Laser Blaster Interface Device
#   
#
#----------------------------------------------------------------
class LaserWeapon:

#--------------------Class Behavior--------------------------
    #Possible states:
    #   0 = off and disabled
    #   1 = idle
    #   2 = firingPrimary
    #   3 = firingSecondary
    #   4 = primedForSecondary
    #   5 = overheated

    currentState = 0

    #Other attributes that define LaserWeapon Behavior
    weaponHeat = 0
    coolingSpeed = 1000     #milliseconds between barrel cooling update, will reduce heat by 1+barrel Spin on update
    heatUpPrimary = 20      #ammount of "heat" generated by primary shot
    heatUPSecondary = 60    #ammount of "heat" generated by primary shot
    firingDelay = 300       #delay weapon remains in a firing state. If not polled in time, shots are lost.
    
    #Timer
    oldTime=0 
    newTime=0


#--------------------Sensors and Actors------------------------------------------

    #communication code attributes - access over getter functions
    code_BarrelAnimation ="0"               # FastLED animation string
    code_MuzzleAnimation ="0"               # FastLED animation string
    code_RumbleAnimation ="0"               # code for Rumble is one byte
    code_LaserFire ="0"                     # code for laser outputs 0,1,2

    #sensor attributes
    v_primaryButton = 0
    v_secondaryButton = 0
    v_thumbButton = 0
    v_barrelSpin = 0

    #animation attributes
    a_barrel = 0                            #0 - OFF, 1 - idle animation (heat indicating), 2 - primary firing, 3 - secondary firing, 4 - overheated
    a_muzzle = 0                            #0 - OFF, 1 - primary firing, 2 - primed for secondary, 3 - secondary firing, 4 - overheated
    a_rumble = 0                            #0 - OFF, 1 - primary firing, 2 - primed for secondary, 3 - secondary firing, 4 - overheated
    a_laser = 0                             #0 - OFF, 1 - primary firing, 2 - secondary firing


#-----------------------------------IO-----------------------------------------

    #Updated the Variables that represent the sensor states
    def set_Input (buttonFlags,barrelCounter):

        try:
            v_primaryButton     = buttonFlags[0]
            v_secondaryButton   = buttonFlags[1]
            v_thumbButton       = buttonFlags[3]
        except Exception, e:
            print("ButtonFlag Argument Passed to Weapon incorrect")


        try:
            v_barrelSpin = barrelCounter
        except Exception, e:
            print("BarrelCounter Argument Passed to Weapon incorrect")

        #run UPDATE
        update_State()



    #Returns if Laser should be fired.
    # 0 - No Laser Fire
    # 1 - Fire Primary Laser
    # 2 - Fire Secondary Laser
    def get_code_LaserFire():

        # FORMAT STUFF THE WAY IT IS NEEDED

        return self.code_LaserFire

    def get_code_BarrelAnimation():

        # FORMAT STUFF THE WAY IT IS NEEDED

        return self.code_BarrelAnimation

    def get_RumbleAnimation():

        # FORMAT STUFF THE WAY IT IS NEEDED

        return self.code_RumbleAnimation

    def get_MuzzleAnimation():

        # FORMAT STUFF THE WAY IT IS NEEDED

        return self.code_MuzzleAnimation


#------------------------------STATE STUFF-------------------------------------

    def update_State():

        #timer
        newTime=time.time()*1000

        if currentState==0: #off
            if v_thumbButton==1:
                currentState = 1

        elif currentState==1: #idle
            #update internal variables

            #   -   weapon heat
            update_WeaponHeat()

            #update IO codes

            #   -   CODE ME PLEASE!!!!

            #transitions to other states
            if weaponHeat >= 255:
                currentState = 5
            elif v_secondaryButton == 1:
                currentState = 4 #
            elif v_primaryButton == 1:
                currentState = 2
            
        
        elif currentState==2: #firingPrimary
            #update internal variables

                #   -   weapon heat
                weaponHeat = min(weaponHeat + heatUpPrimary, 255)

                #update IO codes

                #   -   CODE ME PLEASE!!!! set codeLaserFire to 1

                #transitions to other states
                if newTime-oldTime > firingDelay:
                    currentState = 1 # go back to normal



        elif currentState==3: #firingSecondary
            #update internal variables

                #   -   weapon heat
                weaponHeat = min(weaponHeat + heatUPSecondary, 255)

                #update IO codes

                #   -   CODE ME PLEASE!!!! set codeLaserFire to 2

                #transitions to other states
                if newTime-oldTime > firingDelay:
                    currentState = 1 # go back to normal

        elif currentState==4: #primedForSecondary
            #update internal variables

                #   -   weapon heat
                update_WeaponHeat()

                # UPDATE IO  -   CODE ME PLEASE!!!!

                #transitions to other states
                if v_secondaryButton == 0:
                    currentState = 3 # go to fire the secondary

        elif currentState==5: #overheated
        #update internal variables

                #   -   weapon heat
                update_WeaponHeat()

                # UPDATE IO  -   CODE ME PLEASE!!!!

                #transitions to other states
                if weaponHeat == 0:
                    currentState = 1 #back to idle
       
        #update Timer
        oldTime=newTime



    def update_WeaponHeat():
        #timer
        newTime=time.time()*1000

        if newTime-oldTime > coolingSpeed:
                    weaponHeat = max(weaponHeat - (v_barrelSpin + 1),0)

